Update requirements.txt (#248)
ERROR: Cannot install h-baselines because these package versions have conflicting dependencies.
The conflict is caused by:
    gym 0.14.0 depends on cloudpickle~=1.2.0
    tensorflow-probability 0.8.0 depends on cloudpickle==1.1.1
--> changing tensorflow-probability==0.8.0 to tensorflow-probability==0.9.0 allows dependencies to work